# Generated by Django 2.2.16 on 2020-09-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='reoccurs',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='start_time',
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Menu')),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
            bases=('backend.menu',),
        ),
    ]
