# Generated by Django 2.2.16 on 2020-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.SlugField(editable=False, max_length=64),
        ),
    ]
