# Generated by Django 2.2.16 on 2020-10-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201002_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='super_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.Menu'),
        ),
    ]
