# Generated by Django 2.2.16 on 2020-09-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200928_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Menu')),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
            ],
            bases=('backend.menu',),
        ),
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
