# Generated by Django 2.2.16 on 2020-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200929_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymenu',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
