# Generated by Django 2.2.17 on 2021-02-15 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210214_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
