# Generated by Django 2.2.16 on 2020-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201008_1947'),
    ]

    operations = [
         
        migrations.RemoveField(
            model_name='weeklymenu',
            name='menu_ptr',
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
        migrations.AddField(
            model_name='menu',
            name='end_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='start_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
