# Generated by Django 2.2.17 on 2021-03-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210215_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Item'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='super_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Session'),
        ),
    ]
