# Generated by Django 2.2.17 on 2021-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210314_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, to='backend.Item'),
        ),
    ]
