# Generated by Django 2.2.16 on 2020-10-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201001_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Image'),
        ),
    ]
