# Generated by Django 2.2.17 on 2021-03-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210314_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
        migrations.CreateModel(
            name='MenuUrlName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.SlugField(editable=False, max_length=64)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Menu')),
            ],
        ),
    ]
