# Generated by Django 2.2.17 on 2021-03-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210314_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuurlname',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
