# Generated by Django 2.2.17 on 2021-03-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210314_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuurlname',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.MenuUrlName'),
            preserve_default=False,
        ),
    ]
