# Generated by Django 2.2.17 on 2021-03-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210314_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menuurlname',
            name='menu',
            field=models.ForeignKey(default="0dadddf39e844558b958bfbeaed84703", on_delete=django.db.models.deletion.CASCADE, to='backend.Menu'),
            preserve_default=False,
        ),
    ]
